### ISSUE TITLE
Filtering with q[field_name] not working if field has different name in json

### ISSUE THREAD

**Issue by wateryoma** [wantedly/apig#115]
Filtering with q[field_name] not working if field has different name in json, for example 

``` go
type User struct {
    ID          uint       `gorm:"primary_key;AUTO_INCREMENT" json:"id" form:"id"`
    Pid         uint `json:"uid" form:"uid"`
    CreatedAt   *time.Time `json:"created_at" form:"created_at"`
    UpdatedAt   *time.Time `json:"updated_at" form:"updated_at"`
}
```

GET http://localhost:8080/users?q[uid]=42
gives me 

``` json
{"error":"pq: column \"uid\" does not exist"}
```

but GET http://localhost:8080/users?q[pid]=42 is OK

it's not a big deal for me, but maybe you should mention it in docs, that q[field_name] is more likely q[column_name]

**Comment by shimastripe** [comment]
@wateryoma 
Sorry for late reply and thank you for this issue.
As you say, `q[field_name]` is not accurate.
Please let me think about it. Thanks!

**Comment by luvtechno** [comment]
Hi, sorry for delayed response!

This package is now maintained at https://github.com/shimastripe/apig

Please reopen in the new repo if you are still interested in. 

Thanks!
