### ISSUE TITLE
GOPATH with more than 1 path results in unwanted behavior

### ISSUE THREAD

**Issue by dalu** [wantedly/apig#125]
my
`GOPATH=/home/darko/3go:/home/darko/go`
so I when I `go get` stuff it's placed in `3go`,
and my stuff is in `go`.

however when you `apig new` this then instead writes to the full `GOPATH`.

workaround `GOPATH=$HOME:go apig new -d postgres -u dalu whatever`

But it should be aware of GOPATH having more than 1 value.

GOPATH is a []string, not a string

**Comment by luvtechno** [comment]
Hi, sorry for delayed response!

This package is now maintained at https://github.com/shimastripe/apig

Please reopen in the new repo if you are still interested in. 

Thanks!
