### ISSUE TITLE
Support structs that use gorm.Model

### ISSUE THREAD

**Issue by lfshr** [wantedly/apig#126]
Currently any models that use gorm.Model rather than specifying ID manually are ignored. Models should be picked up when gorm.Model is used.

#### Example
```golang
type Customer struct {
	gorm.Model
	FirstName string
	LastName  string
}
```

**Comment by lfshr** [comment]
I see that there's a PR open for this #122 
Any reason it was never merged?

**Comment by luvtechno** [comment]
Hi, sorry for delayed response!

This package is now maintained at https://github.com/shimastripe/apig

Please reopen in the new repo if you are still interested in. 

Thanks!
