### ISSUE TITLE
apig gen command shows : Invalid import path

### ISSUE THREAD

**Issue by siddheshpujare61** [wantedly/apig#128]
I was trying to implement same plugin in go. 

When i run apig run command on my windows machine, it shows "Invalid import path : github.com\wantedly\Test "

Please help me to rectify this.

**Comment by asaurav025** [comment]
@siddheshpujare61 Same issue occurred to me in Windows but worked fine in Linux environment.
I think its a bug.

**Comment by luvtechno** [comment]
Hi, sorry for delayed response!

This package is now maintained at https://github.com/shimastripe/apig

Please reopen in the new repo if you are still interested in. 

Thanks!
