### ISSUE TITLE
[2016-07-22] Points need to be fixed

### ISSUE THREAD

**Issue by awakia** [wantedly/apig#25]
## About Makefile

- [x] solved

(priority low)

I pretty doubt about necessity of `make deps`

```
make deps
make
make install
```

flow seems really unusual for me. Is there any major app which uses this flow?

If we create makefile, we should follow make standard flow:

```
make
make install
```

## About Target Directory

- [x] solved

```
apig new apig-sample
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/README.md
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/.gitignore
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/main.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/db/db.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/db/pagination.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/router/router.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/middleware/set_db.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/server/server.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/helper/field.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/version/version.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/version/version_test.go
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/controllers/.gitkeep
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/docs/.gitkeep
	create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/models/.gitkeep
===> Created /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample
```

```
git config --global github.user awakia
```

solves this problem, but this is tooooo confusing.

We should somehow solve this problem by asking directory or accepting argument about directory

## About README

- [x] solved

The instruction in README is not understandable...
Maybe users cannot create servers like what we expected.

We should explain more where to write initial file and gorm model file

```
gen command

gen command tells apig to generate files (routes, controllers, documents...) from gorm model files you wrote.
```

## Bugs

- [x] in controller

**Comment by creasty** [comment]
> If we create makefile, we should follow make standard flow:

In this case make is unlikely to be responsible for ensuring dependencies or environments to be ready for following build and installation processes.

In a custom of Unix development, we often do this by `./configure`.

**Comment by awakia** [comment]
@creasty 

In my understanding `./configure` creates makefile by considering environments of the machine.
To install dependency is always in `make` command.

**Comment by creasty** [comment]
Hmm. I think it does both.

**Comment by awakia** [comment]
Anyway, we wrote makefile directly so considering `./configure` makes problem difficult.
I understand go-like dependency is somehow new concept for makefile. So `make deps` is not too bad if other major go vendor uses it. So I just want to get examples of `make deps`

**Comment by awakia** [comment]
Other point is to consider usability.

If there are users who want to use `make deps` and `make` separately, we should split the command.
For example, `make` and `make install` should be separated since there are users who do not want to install command globally.

However, in `make deps` case, since we use glide, we can safely assume installing dependencies does not break other go programs. So almost all people always execute `make deps` and `make`. That is waste of time. So I think we should run both deps part and build part in `make` command
