### ISSUE TITLE
JSON output should pretty format

### ISSUE THREAD

**Issue by shimastripe** [wantedly/apig#60]
# WHY
Heroku-api-design says "Keep JSON minified in all responses".
https://geemus.gitbooks.io/http-api-design/content/en/responses/keep-json-minified-in-all-responses.html

So pretty JSON output is easy to read for human.

# WHAT
gin has pretty JSON output method.

```
c.JSON(200, fieldMap)
```

```
c.IndentedJSON(200, fieldMap)
```

However, gin warned,
> WARNING: we recommend to use this only for development propuses since printing pretty JSON is more CPU and bandwidth consuming. Use Context.JSON() instead.

I think it does not cost so much to convert pretty JSON output.

How do you think?

**Comment by dtan4** [comment]
I think we don't have to prettify JSON as default. As described above article, provide `pretty=true/false` (false is default) option seems to be good.

**Comment by shimastripe** [comment]
OK. And then [gin.GetQuery method](https://godoc.org/github.com/gin-gonic/gin#Context.GetQuery) is checking whether the url query exists.

So I should get rid of the `=true/false` from formatting trigger.

`http://localhost:8080/api/users?pretty`

What do you think about this?

**Comment by dtan4** [comment]
It seems simpler than mine. Looks good 👍
