### ISSUE TITLE
Nest foreign key relations

### ISSUE THREAD

**Issue by shimastripe** [wantedly/apig#75]
cc @awakia  @dtan4 @munisystem 
## WHY

https://geemus.gitbooks.io/http-api-design/content/en/responses/nest-foreign-key-relations.html

<details>
<summary>

Summary Goes Here</summary>

Serialize foreign key references with a nested object, e.g.:

``` json
{
  "name": "service-production",
  "owner": {
    "id": "5d8201b0..."
  },
  // ...
}
```

Instead of e.g.:

``` json
{
  "name": "service-production",
  "owner_id": "5d8201b0...",
  // ...
}
```

This approach makes it possible to inline more information about the related resource without having to change the structure of the response or introduce more top-level response fields, e.g.:

``` json
{
  "name": "service-production",
  "owner": {
    "id": "5d8201b0...",
    "name": "Alice",
    "email": "alice@heroku.com"
  },
  // ...
}
```

</details>
## WHAT

Then now apig works this.

``` json
{
  "name": "service-production",
  "owner_id": "5d8201b0...",
  "owner": null
}
```

so I think apig should work in this way.

``` json
{
  "name": "service-production",
  "owner": {
    "id": "5d8201b0...",
  }
}
```

I want to hear everyone's opinion.
## HOW
- How to identify foreign key ?

`gorm` has `gorm:"ForeignKey:Profile"` tag.

But `gorm` works `json:profile_id` tag as `gorm:"ForeignKey:Profile"` without `gorm:"ForeignKey:Profile"`.

``` go
ProfileID   uint      `json:"profile_id"`
// => ProfileID   uint      `json:"profile_id" gorm:"ForeignKey:Profile"`
```

So I don't know what is better that `gorm:"ForeignKey:XXX"` was mandatory.

**Comment by awakia** [comment]
> gorm:"ForeignKey:XXX" was mandatory

No way.
Since gorm can understand that relation, we can understand it as well.

> I want to hear everyone's opinion.

I like this idea, but it's not high priority.
This api is a kind of simple replacement of direct access of SQL database, so current response is not too bad.
If you can find simple and clear implementation to achieve this, I'm positive. Please keep in mind that you should not make the code too dirty to achieve this.
